name: Trigger Hugo Config Build

on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    runs-on: Ubuntu-22.04
    steps:
      - name: Trigger build in hugo-config
        uses: actions/github-script@main
        with:
          script: |
            const configRepoOwner = 'debuginn';
            const configRepoName = 'blog';
            const workflowName = 'deploy';

            const response = await octokit.rest.actions.createWorkflowDispatch({
              owner: configRepoOwner,
              repo: configRepoName,
              workflow_id: workflowName,
              ref: 'main',
            });

            if (response.status != 201) {
              throw new Error('Failed to trigger workflow');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }} // 使用存储的个人访问令牌